Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@lopocode 
Learn Git and GitHub without any code!
Using the Hello World guide, you’ll start a branch, write comments, and open a pull request.


lopocode
/
instautomation
forked from ely-saucelabs/instautomation
0
015
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
instautomation/.github/workflows/ci-setup.yml
@KarlaSauceLabs
KarlaSauceLabs Rename ci.yml to ci-setup.yml
Latest commit c048946 2 days ago
 History
 1 contributor
43 lines (40 sloc)  1009 Bytes
  
# From: 
# * https://github.com/ruby/setup-ruby
# * https://github.com/actions/setup-node
  
name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12' 
    - name: Cache Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-    
    - name: Build and test
      run: |
        yarn install --check-files
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails test
        bundle exec rails test:system
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
